### ISSUE TITLE
Fix ninja -C build  | No such file or directory errors

### ISSUE THREAD

**Issue by ItsVinodAdari** [statusengine/broker#23]
unable to execute the ninja -C build and getting the ``` No such file or directory ``` errors

error occurred in ubuntu 20

![statusengine_error1](https://user-images.githubusercontent.com/31367403/110442959-6840b480-80e1-11eb-8875-7cd3eb42c799.png)
![statusengine_error2](https://user-images.githubusercontent.com/31367403/110442967-6a0a7800-80e1-11eb-85fd-f710d5b693ce.png)

Thank you

**Comment by ItsVinodAdari** [comment]
I haven't installed Naemon, I'm installing for Nagios(4.4.6)

I'm following these steps:

- git clone https://github.com/statusengine/broker.git
- meson setup -Dnagios=true -Dnagios_include_dir=/opt/nagios/include build
- ninja -C build ( here error occurring )
- ninja -C build install

Thank you

**Comment by nook24** [comment]
Nagios users need to install the Nagios header files manually, when compiling Nagios itself:
```
make install install-devel
```
I added this to the docs: https://statusengine.org/tutorials/install-nagios4-focal/

After this you can install and load the Statusengine Broker as described:
```
apt-get install git python3-pip gcc g++ cmake build-essential libglib2.0-dev libgearman-dev uuid-dev libuchardet-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev gearman-job-server
pip3 install meson ninja

cd /tmp
git clone https://github.com/statusengine/broker.git broker
cd broker/

meson setup -Dnagios=true -Dnagios_include_dir=/opt/nagios/include build
ninja -C build

mkdir -p /opt/statusengine/lib
cp build/src/libstatusengine.so /opt/statusengine/lib/libstatusengine.so
```

Regards,

Daniel

**Comment by ItsVinodAdari** [comment]
Thank you Daniel, It is working fine now
