### ISSUE TITLE
librabbitmq-dev always required?

### ISSUE THREAD

**Issue by nook24** [statusengine/broker#24]
In https://github.com/statusengine/interface/issues/47 @tinoklauer  had some issues building the Statusengine Broker using:
```
-Drabbitmq=false
```

which results into:
```
Error: Could not load module '/opt/statusengine/lib/libstatusengine.so' -> /opt/statusengine/lib/libstatusengine.so: undefined symbol: amqp_empty_bytes

meson setup -Dnagios=true -Dnagios_include_dir=/opt/nagios/include -Drabbitmq=false build
```

We should check if this is an error in the docs or an error in the broker module.

**Comment by jabdr** [comment]
In my test there was no link to any rabbitmq lib when rabbitmq was set to false. Could you reproduce it somewhere? Maybe he had built it before with rabbitmq and it was cached? @nook24

**Comment by tinoklauer** [comment]
Hi,

here the script for reproduce. I change the script from [nook24](https://gist.githubusercontent.com/nook24/0e5f870f6492d6a8cbb69982654aa934/raw/1a8736f2b0d0938016f04a9cbcea8b12fbc30072/statusengine_development_setup.sh) for Debian 10.

[Download script](https://gist.githubusercontent.com/tinoklauer/95eb4c88c7fc04d291f3383d9c5c1ecc/raw/1198f7bf8d63b3678fa9c72f3a7d3a34bd594a7a/statusengine_development_setup.sh)

Testet in Debian 10

thx

**Comment by jabdr** [comment]
@tinoklauer Thanks for the bug report. It should work with the latest commit as intended.

**Comment by tinoklauer** [comment]
@jabdr I tested and it works. thx
