### ISSUE TITLE
Delete Performancedata from "check"

### ISSUE THREAD

**Issue by tinoklauer** [statusengine/broker#25]
Hi,

is it possible to reset(delete) performance data from one check for example localhost - CPU load?

thx

**Comment by nook24** [comment]
Yes of course.

**MySQL and CrateDB**
```SQL
DELETE FROM statusengine_perfdata WHERE hostname='localhost' AND service_description='Ping';
```

**Graphite**
```
rm -rf /var/lib/graphite/whisper/statusengine/localhost/Ping
```

**Elasticsearch** is a bit trickier, you need to send a delete request like documented: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html

**Comment by tinoklauer** [comment]
thanks
