### ISSUE TITLE
With the different views (24h 1w 1m) there are different down tims

### ISSUE THREAD

**Issue by tinoklauer** [statusengine/broker#27]
Hi,

why i have different downtimes?

System Debian 10 with Nagios 4 (4.4.6)

...
check_interval                5
retry_interval                  1
...
![Bild 2](https://user-images.githubusercontent.com/77441570/132364908-268629bb-776d-4d5c-a086-7f788f025a33.jpg)
![Bild3](https://user-images.githubusercontent.com/77441570/132365085-912ab3b6-131c-4d11-9179-6b165c54a0cf.png)

**Comment by nook24** [comment]
It would be good if you create the issue to the corresponding repositories: https://github.com/statusengine/interface

The Chart will always display 100 (or 500 I'm not sure) datapoints. So in the background a "compression" needs to be done. The system will average various data points together. Also the timestamp is an average in this case.

https://github.com/statusengine/interface/blob/master/src/Controller/ServicePerfdata.php#L72-L112
Maybe not the best implementation, idk

You can try to increase the limit to get a more accurate chart but this could lead to browser crashes.

**Comment by tinoklauer** [comment]
Change to https://github.com/statusengine/interface/issues/51
