### ISSUE TITLE
Unable to setup meson

### ISSUE THREAD

**Issue by haijubin** [statusengine/broker#28]
I am trying to configure meson as mentioned in the guie using below command. 
**_meson setup -Dnagios=true -Dnagios_include_dir=/usr/include/nagios build_**

But I am getting below error.
**_Run-time dependency uchardet found: NO (tried pkgconfig and cmake)_**
----------------------------------------------------------------------------------------------
# meson setup -Dnagios=true -Dnagios_include_dir=/usr/include/nagios build
The Meson build system
Version: 0.60.0
Source dir: /tmp/broker
Build dir: /tmp/broker/build
Build type: native build
Project name: statusengine-broker
Project version: 4.2.0
C++ compiler for the host machine: c++ (gcc 4.8.5 "c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)")
C++ linker for the host machine: c++ ld.bfd 2.27-44
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.27.1)
Found CMake: /usr/bin/cmake (3.17.5)
Run-time dependency uchardet found: NO (tried pkgconfig and cmake)

meson.build:6:0: ERROR: Dependency "uchardet" not found, tried pkgconfig and cmake

A full log can be found at /tmp/broker/build/meson-logs/meson-log.txt
----------------------------------------------------------------------------------------------

uchardet is already installed and on latest version.
Installed:
  uchardet.x86_64 0:0.0.6-1.el7

Could you please guide me to fix this?

Thanks,
Jubin

**Comment by nook24** [comment]
How about installing uchardet?
```
yum install uchardet uchardet-devel
```

**Comment by haijubin** [comment]
Thanks for the quick respose.

Will check and update.

**Comment by haijubin** [comment]
Issue resolved after installing devel package. 

Now I am facing below issue while building.
-------------------------------------------------------------------
ninja -C build -d explain -d keepdepfile -d keeprsp
ninja: Entering directory `build'
ninja explain: deps for 'src/libstatusengine.so.p/Nebmodule.cpp.o' are missing
ninja explain: src/libstatusengine.so.p/Nebmodule.cpp.o is dirty
ninja explain: deps for 'src/libstatusengine.so.p/Statusengine.cpp.o' are missing
ninja explain: src/libstatusengine.so.p/Statusengine.cpp.o is dirty
ninja explain: deps for 'src/libstatusengine.so.p/MessageHandler_MessageHandlerList.cpp.o' are missing
ninja explain: src/libstatusengine.so.p/MessageHandler_MessageHandlerList.cpp.o is dirty
ninja explain: deps for 'src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o' are missing
ninja explain: src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o is dirty
ninja explain: src/libstatusengine.so is dirty
[1/5] Compiling C++ object src/libstatusengine.so.p/Statusengine.cpp.o
FAILED: src/libstatusengine.so.p/Statusengine.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/include/json-c -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem.. -isystem. -isystem../vendor -DBUILD_NAGIOS -DWITH_RABBITMQ -MD -MQ src/libstatusengine.so.p/Statusengine.cpp.o -MF src/libstatusengine.so.p/Statusengine.cpp.o.d -o src/libstatusengine.so.p/Statusengine.cpp.o -c ../src/Statusengine.cpp
In file included from ../src/nagios/common.h:25:0,
                 from ../src/nagios/nagios.h:28,
                 from ../src/nagios/broker.h:26,
                 from ../src/Nebmodule.h:13,
                 from ../src/Statusengine.h:8,
                 from ../src/Statusengine.cpp:1:
../src/nagios/shared.h:5:27: fatal error: lib/libnagios.h: No such file or directory
 #include "lib/libnagios.h"
                           ^
compilation terminated.
[2/5] Compiling C++ object src/libstatusengine.so.p/Nebmodule.cpp.o
FAILED: src/libstatusengine.so.p/Nebmodule.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/include/json-c -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem.. -isystem. -isystem../vendor -DBUILD_NAGIOS -DWITH_RABBITMQ -MD -MQ src/libstatusengine.so.p/Nebmodule.cpp.o -MF src/libstatusengine.so.p/Nebmodule.cpp.o.d -o src/libstatusengine.so.p/Nebmodule.cpp.o -c ../src/Nebmodule.cpp
In file included from ../src/nagios/common.h:25:0,
                 from ../src/nagios/nagios.h:28,
                 from ../src/nagios/broker.h:26,
                 from ../src/Nebmodule.h:13,
                 from ../src/Nebmodule.cpp:1:
../src/nagios/shared.h:5:27: fatal error: lib/libnagios.h: No such file or directory
 #include "lib/libnagios.h"
                           ^
compilation terminated.
[3/5] Compiling C++ object src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o
FAILED: src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/include/json-c -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem.. -isystem. -isystem../vendor -DBUILD_NAGIOS -DWITH_RABBITMQ -MD -MQ src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o -MF src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o.d -o src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o -c ../src/MessageHandler/RabbitmqClient.cpp
In file included from ../src/nagios/common.h:25:0,
                 from ../src/nagios/nagios.h:28,
                 from ../src/nagios/broker.h:26,
                 from ../src/Nebmodule.h:13,
                 from ../src/NagiosObject.h:7,
                 from ../src/MessageHandler/MessageHandler.h:9,
                 from ../src/MessageHandler/RabbitmqClient.h:3,
                 from ../src/MessageHandler/RabbitmqClient.cpp:1:
../src/nagios/shared.h:5:27: fatal error: lib/libnagios.h: No such file or directory
 #include "lib/libnagios.h"
                           ^
compilation terminated.
ninja: build stopped: subcommand failed.
----------------------------------------------------------------------------------------
Meson setup completed successfully.

he Meson build system
Version: 0.60.1
Source dir: /tmp/broker
Build dir: /tmp/broker/build
Build type: native build
Project name: statusengine-broker
Project version: 4.2.0
C++ compiler for the host machine: c++ (gcc 4.8.5 "c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)")
C++ linker for the host machine: c++ ld.bfd 2.27-44
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.27.1)
Run-time dependency uchardet found: YES 0.0.6
Run-time dependency gearmand found: YES 1.1.12
Run-time dependency librabbitmq found: YES 0.8.0
Run-time dependency json-c found: YES 0.11
Build targets in project: 1

statusengine-broker 4.2.0

  User defined options
    gearman: false
    nagios : true

Found ninja-1.10.2.git.kitware.jobserver-1 at /usr/local/bin/ninja
------------------------------------------------------------------------------------------
libnagios.h file is available under /tmp/broker/devtools/ci/nagios/lib

drwxr-xr-x 2 root root 4096 Nov  3 13:26 .
drwxr-xr-x 3 root root 4096 Nov  3 13:26 ..
-rw-r--r-- 1 root root 4669 Nov  3 13:26 bitmap.h
-rw-r--r-- 1 root root 4358 Nov  3 13:26 dkhash.h
-rw-r--r-- 1 root root 2245 Nov  3 13:26 fanout.h
-rw-r--r-- 1 root root 5810 Nov  3 13:26 iobroker.h
-rw-r--r-- 1 root root 6132 Nov  3 13:26 iocache.h
-rw-r--r-- 1 root root 7528 Nov  3 13:26 kvvec.h
-rw-r--r-- 1 root root  566 Nov  3 13:26 libnagios.h
-rw-r--r-- 1 root root 3553 Nov  3 13:26 lnag-utils.h
-rw-r--r-- 1 root root 2783 Nov  3 13:26 nsock.h
-rw-r--r-- 1 root root 3274 Nov  3 13:26 nspath.h
-rw-r--r-- 1 root root 3227 Nov  3 13:26 nsutils.h
-rw-r--r-- 1 root root 1569 Nov  3 13:26 nwrite.h
-rw-r--r-- 1 root root 5293 Nov  3 13:26 pqueue.h
-rw-r--r-- 1 root root 4612 Nov  3 13:26 runcmd.h
-rw-r--r-- 1 root root 5133 Nov  3 13:26 skiplist.h
-rw-r--r-- 1 root root  205 Nov  3 13:26 snprintf.h
-rw-r--r-- 1 root root 5600 Nov  3 13:26 squeue.h
-rw-r--r-- 1 root root 2120 Nov  3 13:26 t-utils.h
-rw-r--r-- 1 root root 4093 Nov  3 13:26 worker.h

**Comment by nook24** [comment]
Probably the same as https://github.com/statusengine/broker/issues/31#issuecomment-1289203554
