### ISSUE TITLE
I have some error to install broker winth nagios

### ISSUE THREAD

**Issue by bickerabc** [statusengine/broker#29]
root@test:/tmp/broker# meson setup -Dnagios=true -Dnagios_include_dir=/opt/nagios build -Drabbitmq=false
The Meson build system
Version: 0.60.0
Source dir: /tmp/broker
Build dir: /tmp/broker/build
Build type: native build
Project name: statusengine-broker
Project version: 4.2.0
C++ compiler for the host machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency uchardet found: YES 0.0.6
Run-time dependency gearmand found: YES 1.1.18+ds
Run-time dependency librabbitmq found: YES 0.8.0
Run-time dependency json-c found: YES 0.12.1
Build targets in project: 1

statusengine-broker 4.2.0

  User defined options
    nagios            : true
    nagios_include_dir: /opt/nagios
    rabbitmq          : false

Found ninja-1.10.2.git.kitware.jobserver-1 at /usr/local/bin/ninja

Is' OK,But next setup have some error like this:

root@test:/tmp/broker# ninja -C build
ninja: Entering directory `build'
[1/5] Compiling C++ object src/libstatusengine.so.p/Nebmodule.cpp.o
FAILED: src/libstatusengine.so.p/Nebmodule.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/inc                     lude/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pc                     h -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem/opt/nagios                      -isystem../vendor -DBUILD_NAGIOS -DWITH_GEARMAN -MD -MQ src/libstatusengine.so.p                     /Nebmodule.cpp.o -MF src/libstatusengine.so.p/Nebmodule.cpp.o.d -o src/libstatus                     engine.so.p/Nebmodule.cpp.o -c ../src/Nebmodule.cpp
In file included from ../src/Nebmodule.cpp:1:0:
../src/Nebmodule.h:13:10: fatal error: nagios/broker.h: No such file or director                     y
 #include <nagios/broker.h>
          ^~~~~~~~~~~~~~~~~

**Comment by sistemmsn** [comment]
**tested nagios 4.4.7 and centos 7.5**

![image](https://user-images.githubusercontent.com/38023703/173620051-1792c0a8-e754-465a-8ab4-8252f7169928.png)
![image](https://user-images.githubusercontent.com/38023703/173620182-7c478e51-121f-481f-8e65-7f34de65e32c.png)

**Comment by nook24** [comment]
Tested Nagios 4.4.8 on CentOS 8.5 today. No issues 🤷‍♂️

https://github.com/statusengine/broker/issues/31
