### ISSUE TITLE
CentOS 8 discontinuation and unsupported

### ISSUE THREAD

**Issue by emjhay2004** [statusengine/broker#30]
Just want to ask some of your thoughts.

Today, we plan to install the StatusEngine in our NAGIOS production, but we heard the news that the CentOS 8 is being discontinued or unsupported starting this December 2021. Now, upon going through the CentOS 8 guide for Broker, some packages are not available nor the Gearman is available for install even if I use the http://rpms.remirepo.net/enterprise/remi-release-8.rpm repo.

Would you recommend for us to move to other Operating System like Ubuntu so that we can use StatusEngine for NAGIOS?

**Comment by nook24** [comment]
I'm not an CentOS / RHEL user at all. And probably never will be. With that said, I would always recommend to go with Ubuntu bc it's my personal favorite and you don't have any issues with missing packages.

> but we heard the news that the CentOS 8 is being discontinued or unsupported starting this December 2021

There are plenty alternatives to CentOS like _Rocky Linux_, _AlmaLinux_ or _Oracle Linux_ just to name a few.

I updated the docs for RHEL 8.5: https://statusengine.org/broker/#installation tested on `AlmaLinux release 8.5 (Arctic Sphynx)`

---

You can also take a look at [openITCOCKPIT](https://openitcockpit.io/). It also uses Statusengine in the background and comes with tons of extra goodies. The free and open source community edition is only available for Ubuntu and Debian.  RHEL is supported but requires an subscription.
