### ISSUE TITLE
ninja -C build fails on CentOS with Nagios

### ISSUE THREAD

**Issue by avisht7** [statusengine/broker#31]
Tried following the instructions here as well as the broker instruction on statusengineui site - https://statusengine.org/broker#installation
BUT ninja -C build keeps on failing.
What am i missing and why is it failing??
I'm running with Nagios on CentOS7.6.

Error:
bash#ninja -C build install
ninja: Entering directory `build'
[1/7] Compiling C++ object src/libstatusengine.so.p/Nebmodule.cpp.o
FAILED: src/libstatusengine.so.p/Nebmodule.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/include/json-c -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem/usr/local/nagios/include -isystem../vendor -DBUILD_NAGIOS -DWITH_GEARMAN -DWITH_RABBITMQ -MD -MQ src/libstatusengine.so.p/Nebmodule.cpp.o -MF src/libstatusengine.so.p/Nebmodule.cpp.o.d -o src/libstatusengine.so.p/Nebmodule.cpp.o -c ../src/Nebmodule.cpp
In file included from ../src/Nebmodule.cpp:1:0:
../src/Nebmodule.h:13:27: fatal error: nagios/broker.h: No such file or directory
 #include <nagios/broker.h>
                           ^
compilation terminated.
[2/7] Compiling C++ object src/libstatusengine.so.p/Statusengine.cpp.o
FAILED: src/libstatusengine.so.p/Statusengine.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/include/json-c -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem/usr/local/nagios/include -isystem../vendor -DBUILD_NAGIOS -DWITH_GEARMAN -DWITH_RABBITMQ -MD -MQ src/libstatusengine.so.p/Statusengine.cpp.o -MF src/libstatusengine.so.p/Statusengine.cpp.o.d -o src/libstatusengine.so.p/Statusengine.cpp.o -c ../src/Statusengine.cpp
In file included from ../src/Statusengine.h:8:0,
                 from ../src/Statusengine.cpp:1:
../src/Nebmodule.h:13:27: fatal error: nagios/broker.h: No such file or directory
 #include <nagios/broker.h>
                           ^
compilation terminated.
[3/7] Compiling C++ object src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o
FAILED: src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/include/json-c -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem/usr/local/nagios/include -isystem../vendor -DBUILD_NAGIOS -DWITH_GEARMAN -DWITH_RABBITMQ -MD -MQ src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o -MF src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o.d -o src/libstatusengine.so.p/MessageHandler_RabbitmqClient.cpp.o -c ../src/MessageHandler/RabbitmqClient.cpp
In file included from ../src/NagiosObject.h:7:0,
                 from ../src/MessageHandler/MessageHandler.h:9,
                 from ../src/MessageHandler/RabbitmqClient.h:3,
                 from ../src/MessageHandler/RabbitmqClient.cpp:1:
../src/Nebmodule.h:13:27: fatal error: nagios/broker.h: No such file or directory
 #include <nagios/broker.h>
                           ^
compilation terminated.
[4/7] Compiling C++ object src/libstatusengine.so.p/MessageHandler_GearmanClient.cpp.o
FAILED: src/libstatusengine.so.p/MessageHandler_GearmanClient.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/include/json-c -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem/usr/local/nagios/include -isystem../vendor -DBUILD_NAGIOS -DWITH_GEARMAN -DWITH_RABBITMQ -MD -MQ src/libstatusengine.so.p/MessageHandler_GearmanClient.cpp.o -MF src/libstatusengine.so.p/MessageHandler_GearmanClient.cpp.o.d -o src/libstatusengine.so.p/MessageHandler_GearmanClient.cpp.o -c ../src/MessageHandler/GearmanClient.cpp
In file included from ../src/NagiosObject.h:7:0,
                 from ../src/MessageHandler/MessageHandler.h:9,
                 from ../src/MessageHandler/GearmanClient.h:3,
                 from ../src/MessageHandler/GearmanClient.cpp:1:
../src/Nebmodule.h:13:27: fatal error: nagios/broker.h: No such file or directory
 #include <nagios/broker.h>
                           ^
compilation terminated.
[5/7] Compiling C++ object src/libstatusengine.so.p/MessageHandler_MessageHandlerList.cpp.o
FAILED: src/libstatusengine.so.p/MessageHandler_MessageHandlerList.cpp.o
c++ -Isrc/libstatusengine.so.p -Isrc -I../src -I/usr/include/uchardet -I/usr/include/json-c -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -g -fPIC -isystem/usr/local/nagios/include -isystem../vendor -DBUILD_NAGIOS -DWITH_GEARMAN -DWITH_RABBITMQ -MD -MQ src/libstatusengine.so.p/MessageHandler_MessageHandlerList.cpp.o -MF src/libstatusengine.so.p/MessageHandler_MessageHandlerList.cpp.o.d -o src/libstatusengine.so.p/MessageHandler_MessageHandlerList.cpp.o -c ../src/MessageHandler/MessageHandlerList.cpp
In file included from ../src/LogStream.h:5:0,
                 from ../src/IStatusengine.h:3,
                 from ../src/MessageHandler/MessageHandlerList.h:7,
                 from ../src/MessageHandler/MessageHandlerList.cpp:1:
../src/Nebmodule.h:13:27: fatal error: nagios/broker.h: No such file or directory
 #include <nagios/broker.h>
                           ^
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by nook24** [comment]
Your system is looking for the nagios header files to include. For Nagios, you have to manually pass the location of the files. 

It is very important that you had run `make install-devel` when you were installing Nagios Core. Otherwise the files are missing on your system. I have added this line also to the docs: https://statusengine.org/tutorials/install-nagios4-centos8/

If you have installed Nagios via yum, there is probably a `nagios-devel` package available.

I have tested the installation on CentOS 8.5 with Nagios Core 4.4.8.

1. Install Nagios Core like described: https://statusengine.org/tutorials/install-nagios4-centos8/
2. Install the Statusengine Broker Module (for Nagios Core)
```
git clone https://github.com/statusengine/broker.git broker
cd broker/

# Very important! Set the path to the Nagios include files
meson setup -Dnagios=true -Dnagios_include_dir=/opt/nagios/include build

ninja -C build

mkdir -p /opt/statusengine/lib
cp build/src/libstatusengine.so /opt/statusengine/lib/libstatusengine.so
```
